/**
 * Commentaires sarcastiques selon le score
 * Références geek & cinéma
 */

export const SCORE_COMMENTS = {
  perfect: [
    "🏆 Même la NSA est jalouse. Tony Stark approuverait.",
    "🧙 \"You shall not pass!\" — Gandalf aux hackers. Littéralement.",
    "🖖 Spock trouve ça fascinant. Moi aussi, j'avoue.",
    "🤖 \"I'll be back\" qu'il disait. Bah non, pas ici.",
    "🎮 Achievement Unlocked: Le dev sécu a eu sa prime.",
    "🦸 Niveau Avengers. Nick Fury veut votre numéro.",
    "🧪 Breaking Bad, mais c'est la sécurité qui est pure à 99.1%.",
    "🎬 Oscar de la meilleure sécurité. Discours de remerciement ?",
    "🏰 Fort Knox a appelé. Ils veulent des conseils.",
    "🚀 NASA niveau sécurité. Houston n'a aucun problème.",
    "🎯 Bullseye. Même Hawkeye est impressionné.",
    "⚡ \"I am inevitable.\" — Votre pare-feu aux hackers.",
    "🧊 Elsa : \"The cold never bothered me anyway.\" Les hackers non plus, visiblement.",
    "🎭 Standing ovation. Le rideau peut tomber.",
    "🏅 Médaille d'or. Pas de dopage, juste du talent.",
    "🌟 \"To infinity and beyond!\" — Votre score de sécurité.",
    "🎪 Le spectacle est terminé. Les hackers peuvent rentrer chez eux.",
    "🍿 Marvel peut faire un film sur votre infrastructure.",
    "🛸 Les aliens ont scanné votre site. Ils sont repartis bredouilles.",
    "🎖️ Légion d'honneur de la cybersécurité. Champagne."
  ],
  excellent: [
    "🦇 Presque Batman. Manque juste la Batcave et les milliards.",
    "🛡️ Le hacker moyen passera son chemin. Le bon aussi, probablement.",
    "🌌 \"May the Force be with you.\" Elle l'est. Presque trop.",
    "🐉 Dracarys sur les vulnérabilités. Il en reste une ou deux.",
    "😌 Paranoïaque assumé. J'aime ça.",
    "🎬 Sequel en préparation. Le premier opus était solide.",
    "🧝 Legolas approuve. Il voit les failles à 10km. Y'en a pas beaucoup.",
    "🚂 Poudlard Express : destination sécurité. Presque arrivé.",
    "🦁 Simba est devenu roi. Votre site aussi, presque.",
    "🎸 Highway to Hell pour les hackers. AC/DC approuve.",
    "🍕 Les Tortues Ninja protègent votre serveur. Cowabunga!",
    "🤺 En garde ! Votre site a pris des cours d'escrime.",
    "🎲 Nat 19 au dé de sécurité. Presque un crit.",
    "🧩 Puzzle presque complet. Il manque une pièce sous le canapé.",
    "🏎️ Fast & Furious, mais avec de la sécurité. Vin Diesel approuve.",
    "🦈 Les Dents de la Mer, mais c'est vous le requin.",
    "🎻 Sherlock a enquêté. \"Élémentaire\", qu'il a dit.",
    "🌊 Aquaman protège vos données. Elles sont au sec.",
    "🦅 Aigle royal de la sécurité. Vue perçante sur les menaces.",
    "🎯 Robin des Bois tire dans le mille. Ou presque."
  ],
  good: [
    "🤷 \"With great power...\" Ouais, on n'y est pas encore, Peter.",
    "🧙 Dumbledore dirait : \"Pas mal, Harry. Mais peut mieux faire.\"",
    "🎮 Tutoriel terminé. Le vrai boss arrive bientôt.",
    "☕ Passable. Vous visez la médiocrité ou c'est un accident ?",
    "🚀 Houston, on a presque décollé. Presque.",
    "🎬 Film de série B. Regardable, sans plus.",
    "🍿 Popcorn moyen. Ni salé ni sucré. Juste... là.",
    "🚗 Permis de conduire obtenu. Mais évitez l'autoroute.",
    "📚 Hermione lève les yeux au ciel. \"Acceptable\", soupire-t-elle.",
    "🎲 Jet de dé moyen. Pas de fumble, pas de crit.",
    "🏃 Forest Gump court. Vous, vous marchez.",
    "🎸 Cover band correct. Mais c'est pas les Rolling Stones.",
    "🧊 Titanic : vous avez vu l'iceberg. Reste à l'éviter.",
    "🍕 Pizza surgelée. Ça nourrit, mais bon...",
    "🎭 Figurant dans le film de votre propre sécurité.",
    "🦆 Tous les canards sont alignés. Enfin, la plupart.",
    "🎪 Cirque du Soleil budget réduit. Joli, mais fragile.",
    "🧩 Puzzle 500 pièces. Vous en avez placé 350.",
    "🚦 Feu orange. Vous pouvez passer, mais prudemment.",
    "🎵 Auto-tune activé. La voix originale est perfectible."
  ],
  medium: [
    "😬 \"I've got a bad feeling about this.\" — Moi, en voyant ça.",
    "🤖 C-3PO calcule 87.6% de chances de hack. Optimiste.",
    "🏚️ \"Winter is coming.\" Pour vos données surtout.",
    "🎰 La sécurité par la chance. Stratégie audacieuse, je dois dire.",
    "🧟 The Walking Dead, mais c'est votre site le zombie.",
    "🎬 Film d'horreur où le personnage descend à la cave.",
    "🚪 \"Here's Johnny!\" — Mais la porte est entrouverte.",
    "🎪 Le funambule vacille. Le filet est troué.",
    "🍿 Plot twist : le méchant, c'est votre code.",
    "🏃 Courir dans un couloir sans fin. Style Shining.",
    "🎲 Le MJ vous regarde avec pitié. Mauvais signe.",
    "🧊 \"Let it go\" chante Elsa. Vos données aussi, bientôt.",
    "🦖 Le T-Rex vous a repéré. Ne bougez plus.",
    "🎭 Tragédie grecque en préparation. Chœur antique inclus.",
    "🌪️ \"Toto, I've a feeling we're not in Kansas anymore.\"",
    "🎸 Dissonance cognitive. Et sonore.",
    "🚢 Iceberg droit devant. Et le capitaine est aux toilettes.",
    "🧙 Gandalf hésite entre \"Fuyez\" et \"Pauvres fous\".",
    "🎯 Vous avez touché la cible. Celle d'à côté.",
    "🍕 La pizza est arrivée froide. Et c'était pas la bonne."
  ],
  poor: [
    "💀 \"Game over, man!\" — Même Hudson aurait fait mieux.",
    "🦖 \"Life finds a way.\" Les hackers aussi, visiblement.",
    "🚢 \"I'm the captain now.\" — Signé : n'importe quel script kiddie.",
    "🔮 Mon Skyblog de 2007 était plus sécurisé. Et j'avais 14 ans.",
    "🎮 Dark Souls avait l'air plus accueillant.",
    "🎬 Red Wedding de la cybersécurité. Personne ne survit.",
    "🧟 \"They're coming to get you, Barbara.\" Et vite.",
    "🎪 Le lion s'est échappé. Et il a faim.",
    "☠️ Pirates des Caraïbes, mais c'est vous le trésor.",
    "🎲 Nat 1. Échec critique. Le MJ ricane.",
    "🌋 Mordor avait meilleure réputation.",
    "🤡 Pennywise trouve votre sécurité effrayante. C'est dire.",
    "🎭 Roméo et Juliette, mais les deux meurent au premier acte.",
    "🚀 Challenger, Columbia... Votre site rejoint la liste.",
    "🧊 Le Titanic était mieux préparé. Lui au moins avait des canots.",
    "🦈 Vous nagez avec les requins. Sans cage. Nu.",
    "🎯 Guillaume Tell vise. Vous êtes la pomme.",
    "🏚️ \"Redrum\". Mais à l'endroit c'est pas mieux.",
    "🍕 Pineapple on pizza. Niveau d'hérésie comparable.",
    "🎸 Nickelback de la cybersécurité. Tout le monde souffre."
  ],
  disaster: [
    "🤡 \"Why so serious?\" — Le Joker a fait le code review.",
    "💣 Thanos claque des doigts et vos données disparaissent.",
    "👾 \"All your base are belong to us.\" Littéralement.",
    "☠️ Ce n'est pas un site, c'est un honeypot involontaire.",
    "🎪 Le cirque Barnum de la cybersécurité. Entrée gratuite.",
    "🔥 \"This is fine.\" — Le chien dans les flammes, c'est vous.",
    "💀 Même Voldemort trouve ça dark.",
    "🎬 Snuff movie de la sécurité. Âmes sensibles s'abstenir.",
    "🧟 Patient zéro de l'apocalypse zombie numérique.",
    "🌋 Pompéi avait un meilleur plan d'évacuation.",
    "🤖 Skynet a regardé. Même lui a eu pitié.",
    "🎲 Le dé a explosé. La table aussi.",
    "🚀 SpaceX refuse de vous envoyer sur Mars. Trop risqué.",
    "🦖 L'astéroïde, c'est votre site. Les dinosaures, vos données.",
    "🎭 Greek tragedy? Non. Greek apocalypse.",
    "🧊 Frozen 3 : \"Let it breach\". Sortie immédiate.",
    "🏴‍☠️ Même les pirates trouvent ça trop facile. Pas sport.",
    "🎯 La cible vous a tiré dessus. Retournement de situation.",
    "🍕 Quelqu'un a commandé une pizza avec des anchois ET ananas.",
    "🎸 Yoko Ono chante votre code source. Tout le monde pleure."
  ]
};
